# Generated by Django 3.0.9 on 2020-08-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('kpp', models.SmallIntegerField(choices=[[0, 'Механическая коробка передач'], [1, 'Автоматическая коробка передач'], [2, 'Роботизированная коробка передач']])),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
